#!/usr/bin/env bash
set -euo pipefail

GPU="${GPU:-0}"
WORKERS="${WORKERS:-1}"
PYTHON="${PYTHON:-python}"
SAVE_ROOT="${SAVE_ROOT:-KITE_wo_future}"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":128,"dropout":0.2,"fc_type":"Linear","flow_depth":5,"flow_dim":640,"flow_head":8,"horizon":24,"lr":0.000576,"lradj":"type3","mlp_ratio":8.0,"noise_dropout":0.28,"norm":true,"num_epochs":100,"num_samples":200,"omega":1.2,"p_uncond":0.45,"piror":"pearson","rank":48,"rate":4,"seq_len":168,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/BE/h24"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":128,"dropout":0.2,"fc_type":"Linear","flow_depth":5,"flow_dim":640,"flow_head":8,"horizon":360,"lr":0.000576,"lradj":"type3","mlp_ratio":8.0,"noise_dropout":0.28,"norm":true,"num_epochs":100,"num_samples":200,"omega":1.2,"p_uncond":0.45,"piror":"pearson","rank":48,"rate":4,"seq_len":720,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/BE/h360"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon":10,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":64,"dropout":0.1,"fc_type":"Linear","flow_depth":2,"flow_dim":64,"flow_head":4,"horizon":10,"lr":0.00552,"lradj":"type3","mlp_ratio":8.0,"noise_dropout":0.1,"norm":true,"num_epochs":100,"num_samples":100,"omega":0.55,"p_uncond":0.03,"piror":"pearson","rank":48,"rate":4,"seq_len":60,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/Colbun/h10"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon":30,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":64,"dropout":0.1,"fc_type":"Linear","flow_depth":2,"flow_dim":64,"flow_head":4,"horizon":30,"lr":0.00552,"lradj":"type3","mlp_ratio":8.0,"noise_dropout":0.1,"norm":true,"num_epochs":100,"num_samples":100,"omega":0.55,"p_uncond":0.03,"piror":"pearson","rank":48,"rate":4,"seq_len":180,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/Colbun/h30"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":256,"dropout":0.025,"fc_type":"Linear","flow_depth":5,"flow_dim":640,"flow_head":2,"horizon":24,"lr":0.00081125,"lradj":"type3","mlp_ratio":3.75,"noise_dropout":0.075,"norm":true,"num_epochs":100,"num_samples":400,"omega":0.975,"p_uncond":0.2125,"piror":"pearson","rank":8,"rate":10,"seq_len":168,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/DE/h24"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":256,"dropout":0.025,"fc_type":"Linear","flow_depth":5,"flow_dim":640,"flow_head":2,"horizon":360,"lr":0.00081125,"lradj":"type3","mlp_ratio":3.75,"noise_dropout":0.075,"norm":true,"num_epochs":100,"num_samples":400,"omega":0.975,"p_uncond":0.2125,"piror":"pearson","rank":8,"rate":10,"seq_len":720,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/DE/h360"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":64,"dropout":0.0125,"fc_type":"Linear","flow_depth":3,"flow_dim":512,"flow_head":4,"horizon":24,"lr":0.00177437,"lradj":"type3","mlp_ratio":2.0,"noise_dropout":0.175,"norm":true,"num_epochs":100,"num_samples":200,"omega":1.05,"p_uncond":0.0775,"piror":"pearson","rank":40,"rate":15,"seq_len":168,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/Energy/h24"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":64,"dropout":0.0125,"fc_type":"Linear","flow_depth":3,"flow_dim":512,"flow_head":4,"horizon":360,"lr":0.00177437,"lradj":"type3","mlp_ratio":2.0,"noise_dropout":0.175,"norm":true,"num_epochs":100,"num_samples":200,"omega":1.05,"p_uncond":0.0775,"piror":"pearson","rank":40,"rate":15,"seq_len":720,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/Energy/h360"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":128,"dropout":0.0,"fc_type":"Linear","flow_depth":4,"flow_dim":512,"flow_head":8,"horizon":24,"lr":0.00115,"lradj":"type3","mlp_ratio":4.0,"noise_dropout":0.05,"norm":true,"num_epochs":100,"num_samples":400,"omega":0.7,"p_uncond":0.25,"piror":"pearson","rank":64,"rate":12,"seq_len":168,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/FR/h24"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":128,"dropout":0.0,"fc_type":"Linear","flow_depth":4,"flow_dim":512,"flow_head":8,"horizon":360,"lr":0.00115,"lradj":"type3","mlp_ratio":4.0,"noise_dropout":0.05,"norm":true,"num_epochs":100,"num_samples":400,"omega":0.7,"p_uncond":0.25,"piror":"pearson","rank":64,"rate":12,"seq_len":720,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/FR/h360"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":128,"dropout":0.1,"fc_type":"Linear","flow_depth":2,"flow_dim":512,"flow_head":2,"horizon":24,"lr":0.0009,"lradj":"type3","mlp_ratio":12.0,"noise_dropout":0.1,"norm":true,"num_epochs":100,"num_samples":200,"omega":0.55,"p_uncond":0.1,"piror":"pearson","rank":8,"rate":12,"seq_len":168,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/NP/h24"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":128,"dropout":0.1,"fc_type":"Linear","flow_depth":2,"flow_dim":512,"flow_head":2,"horizon":360,"lr":0.0009,"lradj":"type3","mlp_ratio":12.0,"noise_dropout":0.1,"norm":true,"num_epochs":100,"num_samples":200,"omega":0.55,"p_uncond":0.1,"piror":"pearson","rank":8,"rate":12,"seq_len":720,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/NP/h360"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":64,"dropout":0.05,"fc_type":"Linear","flow_depth":4,"flow_dim":512,"flow_head":8,"horizon":24,"lr":0.000882,"lradj":"type3","mlp_ratio":3.0,"noise_dropout":0.15,"norm":true,"num_epochs":100,"num_samples":200,"omega":0.95,"p_uncond":0.05,"piror":"pearson","rank":16,"rate":16,"seq_len":168,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/PJM/h24"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":64,"dropout":0.05,"fc_type":"Linear","flow_depth":4,"flow_dim":512,"flow_head":8,"horizon":360,"lr":0.000882,"lradj":"type3","mlp_ratio":3.0,"noise_dropout":0.15,"norm":true,"num_epochs":100,"num_samples":200,"omega":0.95,"p_uncond":0.05,"piror":"pearson","rank":16,"rate":16,"seq_len":720,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/PJM/h360"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rappel.csv" --strategy-args '{"horizon":10,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":256,"dropout":0.0,"fc_type":"Linear","flow_depth":3,"flow_dim":96,"flow_head":4,"horizon":10,"lr":0.0014,"lradj":"type3","mlp_ratio":3.0,"noise_dropout":0.1,"norm":true,"num_epochs":100,"num_samples":200,"omega":1.6,"p_uncond":0.45,"piror":"pearson","rank":64,"rate":12,"seq_len":60,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/Rappel/h10"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rappel.csv" --strategy-args '{"horizon":30,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":256,"dropout":0.0,"fc_type":"Linear","flow_depth":3,"flow_dim":96,"flow_head":4,"horizon":30,"lr":0.0014,"lradj":"type3","mlp_ratio":3.0,"noise_dropout":0.1,"norm":true,"num_epochs":100,"num_samples":200,"omega":1.6,"p_uncond":0.45,"piror":"pearson","rank":64,"rate":12,"seq_len":180,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/Rappel/h30"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":128,"dropout":0.1,"fc_type":"Linear","flow_depth":2,"flow_dim":64,"flow_head":2,"horizon":24,"lr":0.00073125,"lradj":"type3","mlp_ratio":6.0,"noise_dropout":0.15,"norm":true,"num_epochs":100,"num_samples":200,"omega":0.45,"p_uncond":0.17,"piror":"pearson","rank":24,"rate":2,"seq_len":168,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/Sdwpfh1/h24"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":128,"dropout":0.1,"fc_type":"Linear","flow_depth":2,"flow_dim":64,"flow_head":2,"horizon":360,"lr":0.00073125,"lradj":"type3","mlp_ratio":6.0,"noise_dropout":0.15,"norm":true,"num_epochs":100,"num_samples":200,"omega":0.45,"p_uncond":0.17,"piror":"pearson","rank":24,"rate":2,"seq_len":720,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/Sdwpfh1/h360"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":128,"dropout":0.0,"fc_type":"Linear","flow_depth":2,"flow_dim":256,"flow_head":2,"horizon":24,"lr":0.0019,"lradj":"type3","mlp_ratio":8.0,"noise_dropout":0.1,"norm":true,"num_epochs":100,"num_samples":200,"omega":0.3,"p_uncond":0.45,"piror":"pearson","rank":40,"rate":24,"seq_len":168,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/Sdwpfh2/h24"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":128,"dropout":0.0,"fc_type":"Linear","flow_depth":2,"flow_dim":256,"flow_head":2,"horizon":360,"lr":0.0019,"lradj":"type3","mlp_ratio":8.0,"noise_dropout":0.1,"norm":true,"num_epochs":100,"num_samples":200,"omega":0.3,"p_uncond":0.45,"piror":"pearson","rank":40,"rate":24,"seq_len":720,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/Sdwpfh2/h360"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":128,"dropout":0.0,"fc_type":"Linear","flow_depth":3,"flow_dim":128,"flow_head":4,"horizon":24,"lr":0.001125,"lradj":"type3","mlp_ratio":8.0,"noise_dropout":0.1,"norm":true,"num_epochs":100,"num_samples":200,"omega":0.4,"p_uncond":0.03,"piror":"pearson","rank":16,"rate":24,"seq_len":168,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/Sdwpfm1/h24"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","batch_size":128,"dropout":0.0,"fc_type":"Linear","flow_depth":3,"flow_dim":128,"flow_head":4,"horizon":360,"lr":0.001125,"lradj":"type3","mlp_ratio":8.0,"noise_dropout":0.1,"norm":true,"num_epochs":100,"num_samples":200,"omega":0.4,"p_uncond":0.03,"piror":"pearson","rank":16,"rate":24,"seq_len":720,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/Sdwpfm1/h360"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon":24,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","aux_loss_weight":0.2,"batch_size":128,"dropout":0.0,"fc_type":"Linear","flow_depth":3,"flow_dim":256,"flow_head":2,"horizon":24,"lr":0.0015,"lradj":"type3","min_sigma":0.1,"mlp_ratio":3.0,"noise_dropout":0.25,"norm":true,"num_epochs":100,"num_samples":200,"num_sampling_steps":5,"omega":0.3,"p_uncond":0.25,"patience":10,"piror":"pearson","rank":48,"rate":20,"seq_len":168,"structure_max":0.75,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/Sdwpfm2/h24"

$PYTHON ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon":360,"target_channel":[-1]}' --model-name "kite.KITE" --model-hyper-params '{"agg_method":"mean","aux_loss_weight":0.2,"batch_size":128,"dropout":0.0,"fc_type":"Linear","flow_depth":3,"flow_dim":256,"flow_head":2,"horizon":360,"lr":0.0015,"lradj":"type3","min_sigma":0.1,"mlp_ratio":3.0,"noise_dropout":0.25,"norm":true,"num_epochs":100,"num_samples":200,"num_sampling_steps":5,"omega":0.3,"p_uncond":0.25,"patience":10,"piror":"pearson","rank":48,"rate":20,"seq_len":720,"structure_max":0.75,"unknown_future_exog_strategy":"zero","use_future_exog":false}' --gpus "$GPU" --num-workers "$WORKERS" --timeout 60000 --save-path "${SAVE_ROOT}/Sdwpfm2/h360"
